using Microsoft.AspNetCore.Mvc;
using YoutubeExplode;
using YoutubeExplode.Videos.ClosedCaptions;

namespace YtTranscribeApi.Controllers;

[ApiController]
[Route("api")]
public class TranscribeController : ControllerBase
{
    private readonly ILogger<TranscribeController> _log;

    public TranscribeController(ILogger<TranscribeController> log)
    {
        _log = log;
    }

    public record TranscribeReq(string url, string? preferLanguage);

    public record TranscribeRes(bool ok, string source, string transcript);

    // ✅ CAPTION-ONLY: video indirme yok, openai yok
    [HttpPost("transcribe")]
    public async Task<IActionResult> Transcribe([FromBody] TranscribeReq req, CancellationToken ct)
    {
        _log.LogInformation("START /api/transcribe (caption-only) url={Url}", req.url);

        if (string.IsNullOrWhiteSpace(req.url))
            return BadRequest(new { ok = false, error = "url required" });

        var yt = new YoutubeClient();

        try
        {
            var lang = NormalizeLang(req.preferLanguage);

            _log.LogInformation("Trying captions only... lang={Lang}", lang);

            var text = await TryGetCaptionAsync(yt, req.url, lang, ct);

            if (!string.IsNullOrWhiteSpace(text))
            {
                _log.LogInformation("Captions FOUND len={Len}", text.Length);
                return Ok(new TranscribeRes(true, "captions", text));
            }

            _log.LogInformation("No captions available");
            return StatusCode(409, new
            {
                ok = false,
                error = "caption_unavailable",
                details = "Bu videonun herkese açık transcript (caption) verisi yok veya sunucudan erişilemiyor.",
                hint = "Audio/video dosyasını /api/transcribe/upload ile gönder (server OpenAI ile çözer)."
            });
        }
        catch (Exception ex)
        {
            _log.LogWarning(ex, "Caption fetch failed");
            return StatusCode(409, new
            {
                ok = false,
                error = "caption_unavailable",
                details = "Caption verisine erişilemedi (IP/region/age/cookie olabilir).",
                hint = "Audio/video dosyasını /api/transcribe/upload ile gönder."
            });
        }
        finally
        {
            _log.LogInformation("END /api/transcribe");
        }
    }

    // (Opsiyonel) Upload endpoint burada dursun (Swagger’da görünmez).
    // Not: OpenAI kodunu burada şu an yazmıyorum çünkü sen “caption-only” istedin.
    [ApiExplorerSettings(IgnoreApi = true)]
    [HttpPost("transcribe/upload")]
    [Consumes("multipart/form-data")]
    public IActionResult UploadPlaceholder()
        => StatusCode(501, new { ok = false, error = "not_implemented", details = "Upload transcribe bu build’de kapalı." });

    // -------- helpers --------

    private static string? NormalizeLang(string? lang)
    {
        if (string.IsNullOrWhiteSpace(lang)) return null;
        lang = lang.Trim().ToLowerInvariant();

        return lang switch
        {
            "turkish" => "tr",
            "türkçe" => "tr",
            "tr" => "tr",
            "english" => "en",
            "ingilizce" => "en",
            "en" => "en",
            _ => lang.Length == 2 ? lang : null
        };
    }

    private static async Task<string?> TryGetCaptionAsync(
        YoutubeClient yt,
        string url,
        string? preferLanguage,
        CancellationToken ct)
    {
        var manifest = await yt.Videos.ClosedCaptions.GetManifestAsync(url, ct);
        if (!manifest.Tracks.Any())
            return null;

        ClosedCaptionTrackInfo? trackInfo = null;

        if (!string.IsNullOrWhiteSpace(preferLanguage))
        {
            trackInfo = manifest.Tracks
                .Where(t => string.Equals(t.Language.Code, preferLanguage, StringComparison.OrdinalIgnoreCase))
                .OrderByDescending(t => t.IsAutoGenerated ? 0 : 1) // manuel > auto
                .FirstOrDefault();
        }

        trackInfo ??= manifest.Tracks
            .OrderByDescending(t => t.IsAutoGenerated ? 0 : 1)
            .FirstOrDefault();

        if (trackInfo is null)
            return null;

        ClosedCaptionTrack track = await yt.Videos.ClosedCaptions.GetAsync(trackInfo, ct);

        var text = string.Join(" ",
            track.Captions.Select(c => c.Text).Where(x => !string.IsNullOrWhiteSpace(x))
        );

        return string.IsNullOrWhiteSpace(text) ? null : text;
    }
}
